### ISSUE TITLE
Extra games may have artificially high Balance scores

### ISSUE THREAD

**Issue by kennedy0** [LudumDare/ludumdare.com#19]
I submitted in the Extra category and chose to opt-out of ratings. As a result, my balance rating keeps going up: as I can rate and review others' entries, but nobody can give a rating to my own. While it has been great for me personally, this seems like unintended behavior.

**Comment by mikekasprzak** [comment]
Yes unintended, but also wrong repository: https://github.com/JammerCore/JammerCore
