### ISSUE TITLE
Cant view ratings for extra games

### ISSUE THREAD

**Issue by dirkinzs** [LudumDare/ludumdare.com#21]
Games in the "Extra" category don't seem to display aggregated ratings. Instead of:
**(_rating category_): (_position_)th ((_average rating_) average from (_total ratings_) ratings)**

they display as:
**(_rating category_): N/Ath (0 average from (_total ratings_) ratings)**

note that position and average rating are displaying default values.

**Comment by mikekasprzak** [comment]
Wrong repository. See https://github.com/JammerCore/JammerCore

Also see this discussion: https://github.com/JammerCore/JammerCore/discussions/2125
